CREATE DATABASE IF NOT EXISTS camagru CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE IF NOT EXISTS camagru.USER (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mail VARCHAR(50) NOT NULL UNIQUE,
  username VARCHAR(30) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  recovery TEXT DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS camagru.IMAGE (
  id INT(6) UNSIGNED AUTO_INCREMENT,
  main LONGTEXT NOT NULL,
  filtered LONGTEXT NOT NULL,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES camagru.USER(id)
);
CREATE TABLE IF NOT EXISTS camagru.COM (
  id INT(6) UNSIGNED AUTO_INCREMENT,
  message TEXT NOT NULL,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user INT UNSIGNED,
  image INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES camagru.USER(id),
  FOREIGN KEY (image) REFERENCES camagru.IMAGE(id)
);
CREATE TABLE IF NOT EXISTS camagru.IMAGE_LIKE (
  id INT(6) UNSIGNED AUTO_INCREMENT,
  user INT UNSIGNED,
  image INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES camagru.USER(id),
  FOREIGN KEY (image) REFERENCES camagru.IMAGE(id)
);