CREATE DATABASE IF NOT EXISTS matcha CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE IF NOT EXISTS matcha.USER (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  state INT(1) NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  login VARCHAR(30) NOT NULL UNIQUE,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  sex VARCHAR(1) NULL,
  orientation VARCHAR(3) NULL,
  address VARCHAR(255) DEFAULT NULL,
  city VARCHAR(255) DEFAULT NULL,
  zipcode INT(5) DEFAULT NULL,
  birthdate DATETIME NULL,
  password TEXT NOT NULL,
  biography TEXT DEFAULT NULL,
  recovery TEXT DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS matcha.IMAGE (
  id INT(6) UNSIGNED AUTO_INCREMENT,
  main LONGTEXT NOT NULL,
  filtered LONGTEXT NOT NULL,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES matcha.USER(id)
);
CREATE TABLE IF NOT EXISTS matcha.COM (
  id INT(6) UNSIGNED AUTO_INCREMENT,
  message TEXT NOT NULL,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user INT UNSIGNED,
  image INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES matcha.USER(id),
  FOREIGN KEY (image) REFERENCES matcha.IMAGE(id)
);
CREATE TABLE IF NOT EXISTS matcha.IMAGE_LIKE (
  id INT(6) UNSIGNED AUTO_INCREMENT,
  user INT UNSIGNED,
  image INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (user) REFERENCES matcha.USER(id),
  FOREIGN KEY (image) REFERENCES matcha.IMAGE(id)
);