<footer id="footer">
    <div class="inner">
        <h2>Nous contacter</h2>
        <ul class="actions">
            <li><span class="icon fa-phone"></span> <a href="#">+33 00 00 00 00 00</a></li>
            <li><span class="icon fa-envelope"></span> <a href="#">contact@matcha.com</a></li>
            <li><span class="icon fa-map-marker"></span> 96 Boulevard Bessières, 75017 Paris</li>
        </ul>
    </div>
    <div class="copyright">
        &copy; <a href="http://afdal.fr">AFDAL</a>
    </div>
</footer>

<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/jquery.scrolly.min.js"></script>
<script src="/assets/js/skel.min.js"></script>
<script src="/assets/js/util.js"></script>
<script src="/assets/js/main.js"></script>

</body>
</html>