<!DOCTYPE HTML>
<html>
<head>
    <title><?php render($title); ?></title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/css/main.css" />
</head>
<body>

<header id="header">
    <nav class="left">
        <a href="#menu"><span>Menu</span></a>
    </nav>
    <a href="<?php render(path($app, 'home')); ?>" class="logo">Matcha</a>
    <nav class="right">
        <?php if(empty($_SESSION["loggued_on_user"])): ?>
            <a href="<?php  render(path($app, 'login')); ?>" class="button alt">Login</a>
        <?php else: ?>
            <a href="<?php  render(path($app, 'logout')); ?>" class="button scrolly">Logout</a>
        <?php endif; ?>
    </nav>
</header>

<nav id="menu">
    <ul class="links">
        <li><a href="<?php render(path($app, 'home')); ?>">Home</a></li>
        <li><a href="<?php render(path($app, 'home')); ?>">Generic</a></li>
        <li><a href="<?php render(path($app, 'home')); ?>">Elements</a></li>
    </ul>
    <ul class="actions vertical">
        <li><a href="<?php render(path($app, 'login')); ?>" class="button fit">Login</a></li>
    </ul>
</nav>
<?php
if (!empty($_SESSION['MAIN_MESSAGE'])){
    echo $_SESSION['MAIN_MESSAGE'];
    unset($_SESSION['MAIN_MESSAGE']);
}
?>
