<?php require('header.phtml')?>
    <section id="main" class="wrapper">
        <div class="inner">
            <h3>Login</h3>

            <form method="post" action="#">
                <div class="row uniform">
                    <div class="12u">
                        <input type="text" name="login" id="login" value="" placeholder="Login" />
                    </div>
                    <div class="12u">
                        <input type="password" name="password" id="password" value="" placeholder="Password" />
                    </div>
                    <!-- Break -->
                    <div class="12u$">
                        <ul class="actions">
                            <li><input type="submit" value="Login" /></li>
                            <li><input type="reset" value="Reset" class="alt" /></li>
                        </ul>
                    </div>
                </div>
            </form>
            <hr/>
        </div>
    </section>
<?php require('footer.phtml')?>