<?php require('header.phtml')?>
    <section id="main" class="wrapper">
        <div class="inner">
            <h3>Signup</h3>

            <form method="post" action="<?php render(path($app, 'signup')) ?>">
                <div class="row uniform">
                    <div class="12u">
                        <input type="text" name="login" id="login" value="" placeholder="Login" required />
                    </div>
                    <div class="12u">
                        <input type="email" name="email" id="email" value="" placeholder="Email" required />
                    </div>
                    <div class="12u">
                        <input type="text" name="firstName" id="firstName" value="" placeholder="First name" required />
                    </div>
                    <div class="12u">
                        <input type="text" name="lastName" id="lastName" value="" placeholder="last name" required />
                    </div>
                    <div class="12u">
                        <input type="password" name="password" id="password" value="" placeholder="Password" required />
                    </div>
                    <div class="12u$">
                        <ul class="actions">
                            <li><input type="submit" value="Signup" /></li>
                        </ul>
                    </div>
                </div>
            </form>
            <hr/>
        </div>
    </section>
<?php require('footer.phtml')?>