<?php require('header.phtml')?>
    <section id="main" class="wrapper">
        <div class="inner">
            <h3>Signup</h3>

            <form method="post" action="#">
                <div class="row uniform">
                    <div class="12u">
                        <input type="text" name="login" id="login" value="" placeholder="Login" />
                    </div>
                    <div class="12u">
                        <input type="email" name="email" id="email" value="" placeholder="Email" />
                    </div>
                    <div class="12u">
                        <input type="text" name="first_name" id="first_name" value="" placeholder="First name" />
                    </div>
                    <div class="12u">
                        <input type="text" name="last_name" id="last_name" value="" placeholder="last name" />
                    </div>
                    <div class="12u">
                        <input type="password" name="password" id="password" value="" placeholder="Password" />
                    </div>
                    <!-- Break -->
                    <div class="12u$">
                        <ul class="actions">
                            <li><input type="submit" value="Signup" /></li>
                        </ul>
                    </div>
                </div>
            </form>
            <hr/>
        </div>
    </section>
<?php require('footer.phtml')?>